version: "2"

volumes:
  postgres_data:
    driver: local
  jdata:

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm

  jbpm:
    container_name: jbpm
    image: jboss/jbpm-server-full
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    ports:
      - 8080:8080
      - 8001:8001
    depends_on:
      - postgres
    volumes:
      - "jdata:/opt/jboss/wildfly/bin"

  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
    depends_on:
      - jbpm
